FROM php:8.2-apache

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
WORKDIR /var/www/html

COPY index.php .

RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

LABEL maintainer="Seu Nome <seuemail@exemplo.com>"
LABEL version="1.0"
LABEL description="PoC de PHP com Load Balancing para desafio DIO"

EXPOSE 80